### ISSUE TITLE
API compatibility broken in 3.8

### ISSUE THREAD

**Issue by bluca** [cpputest/cpputest#1002]
Dear maintainers,

In version 3.8, the following changes broke compatibility with 3.7.x:
- removeAllComparators was renamed to removeAllComparatorsAndCopiers
- withBoolParameter and withBoolParameters were added, and booleans are no longer accepted when using withParameter or withIntParameters

As you might imagine, this sort of breakages are quite disruptive for projects using cpputest. This is especially bad when the same code base is building against multiple distributions releases. In our case, we build for Debian 7 (wheezy), Debian 8 (jessie) and Debian 9 (stretch), and this kind of breakages force us to have litter the test code with ifdefs to work around the differences in the cpputest versions.

Going forward, whenever reasonable and feasible, would it be possible to try and update APIs in a backward-compatible way (eg: add a new removeAllComparatorsAndCopiers function and leave the old one in place, rather than renaming)?

Also it would be very helpful if, when API backward-compatibility is broken, the major version of the project gets incremented. This is a more-or-less universal signal that things will stop working without manual intervention, and distribution maintainers then can take appropriate action.

Thanks for your help and good work!

**Comment by arstrube** [comment]
@bluca Sorry about this. removeAllComparators() should never have been changed like this. Shouldn't withParameter() still accept anything, though? I don't know about the others.

@basvodde :

1. Why did we decide to go this way with removeAllComparators()? Why didn't we simply add removeAllCopiers()?
2. I think in the future, we should be extremely wary when existing tests involving the API need changing. Such tests should never be changed, just new tests added.

**Comment by arstrube** [comment]
@bluca I had a quick look at the code and I can't see any obvious reason why withIntParameters() shouldn't accept a boolean anymore? Can you provide an example test where this fails?

**Comment by bluca** [comment]
withParameter, when using booleans, will build but the test will fail when running. I'll prepare an example and a log, give me a few minutes.

**Comment by bluca** [comment]
Sorry, have to sanitize the example due to license. The actual code is C, the test code is C++. Function under test signature:

`int foo (uint16_t arg1, enum bar arg2, bool arg3)`

Mock definition:

```
extern "C" {
	int foo (uint16_t arg1, enum bar arg2, bool arg3)
	{
		return mock_c()->actualCall("foo")
			->withIntParameters("arg1", arg1)
			->withIntParameters("arg2", (int)arg2)
			->withIntParameters("arg3", arg3)
			->returnValue().value.intValue;
	}
}
```

Mock call in the test body:

```
<setup>
...

mock().expectNCalls(1, "foo")
	.withParameter("arg1", some_uint16
	.withParameter("arg2", ENUM_BAR_A)
	.withParameter("arg3", false)
	.andReturnValue(0);
mock().expectNCalls(1, "foo")
	.withParameter("arg1", some_uint16
	.withParameter("arg2", ENUM_BAR_A)
	.withParameter("arg3", true)
	.andReturnValue(0);
...
<teardown>
mock().checkExpectations();
mock().clear();
mock().removeAllComparatorsAndCopiers();
```

The test works in 3.7.x, but fails with 3.8, with:

```
some_test.cpp:123: error: Failure in TEST(test_too, test_foo_1)
        Mock Failure: Unexpected parameter value to parameter "arg3" to function "foo": <0>
        EXPECTED calls that DID NOT happen related to function: foo
                foo -> int arg1: <99>, int arg2: <2>, bool arg3: <false>
                foo -> int arg1: <99>, int arg2: <2>, bool arg3: <true>
        ACTUAL calls that DID happen related to function: foo
                <none>
        ACTUAL unexpected parameter passed to function: foo
                int arg3: <0>
```

**Comment by arstrube** [comment]
Okay.... That's because the actual calls use the C interface and `withIntParameters()`, whereas the expectations use `withParameter()`, which will use the boolean method. Of course, on the C side, you have to specify which type of parameter you want to work with. This really can't be helped.

There are two ways to go about fixing this:

1. Use withBoolParameter() on the C side, wherever booleans are involved.
2. Write stubs and mocks in C++, using withParameter() in the actual call as well.

I have worked with 2. for quite some time now and I think it is the best approach (keeping you out of trouble like this for good). I found one day that was actually no good reason _not_ to write mocks in C++.

**Comment by arstrube** [comment]
I'm afraid this problem can't be helped, without actually scrapping boolean support.

**Comment by bluca** [comment]
That is fine, sometimes it cannot be helped, thanks for checking.

In these cases, perhaps it would be useful to bump the major version, to signal users and maintainers that code that previously worked might not anymore.

**Comment by arstrube** [comment]
It is unfortunate that nobody ran into this issue before the release.... As for `removeAllComparators()`, I think the problem is basically unnecessary and can be fixed, right @basvodde ? Sorry for that one.

**Comment by uecasm** [comment]
There was briefly an auto-conversion between bool and int, which would have made that test pass.  But it was deemed too error prone to retain, so requires changing the test if you're mixing languages like this.  (In C, a bool is essentially a smaller int anyway, while in C++ they are truly distinct types, even if they appear to be spelled the same.)

> I found one day that was actually no good reason not to write mocks in C++.

There are *some* reasons -- there are still constructs that are valid in C99 or C11 but not valid in C++11 (or later), and a few that are subtly different (such as empty parameter lists).  But if you're careful to avoid the traps it's not hard to write code using the compatible subset of both.

**Comment by arstrube** [comment]
@uecasm the fact that there are those subtle differences can also make writing dummies a lot easier - just omit parameter name(s) and no pesky warnings with -Werror ;-).
