### ISSUE TITLE
Tests fail to compile with Clang 3.7

### ISSUE THREAD

**Issue by offa** [cpputest/cpputest#807]
As stated in #806, cpputest wont compile using clang if tests are enabled.

Here are the errors reported:

```
[…]/cpputest/tests/MemoryLeakWarningTest.cpp:275:5: error: 
      'delete' applied to a pointer that was allocated with 'new[]'; did you
      mean 'delete[]'? [-Werror,-Wmismatched-new-delete]
    delete memory;
    ^
          []
[…]/cpputest/tests/MemoryLeakWarningTest.cpp:273:20: note: 
      allocated with 'new[]' here
    char* memory = new char[100];
                   ^
[…]/cpputest/include/CppUTest/MemoryLeakDetectorNewMacros.h:56:13: note: 
      expanded from macro 'new'
#define new new(__FILE__, __LINE__)
            ^
[…]/cpputest/tests/MemoryLeakWarningTest.cpp:353:5: error: 
      'delete' applied to a pointer that was allocated with 'new[]'; did you
      mean 'delete[]'? [-Werror,-Wmismatched-new-delete]
    delete nonArrayMemoryNoThrow;
    ^
          []
[…]/cpputest/tests/MemoryLeakWarningTest.cpp:347:35: note: 
      allocated with 'new[]' here
    char* nonArrayMemoryNoThrow = new (std::nothrow) char[10];
                                  ^
[…]/cpputest/tests/MemoryLeakWarningTest.cpp:354:5: error: 
      'delete' applied to a pointer that was allocated with 'new[]'; did you
      mean 'delete[]'? [-Werror,-Wmismatched-new-delete]
    delete nonArrayMemoryThrow;
    ^
          []
[…]/cpputest/tests/MemoryLeakWarningTest.cpp:348:33: note: 
      allocated with 'new[]' here
    char* nonArrayMemoryThrow = new char[10];
                                ^
3 errors generated.

```

**Comment by jwgrenning** [comment]
Would it be better to set this compile option so the tests can still run

-Wno-mismatched-new-delete

That is a compile time check which could be hidden from Clang if the 
allocation and deallocation are not in the same compilation unit.

James

--------------------------------------------------------------------------
James Grenning - Author of TDD for Embedded C - wingman-sw.com/tddec
wingman-sw.com
wingman-sw.com/blog
twitter.com/jwgrenning
facebook.com/wingman.sw
[![wingman 
software](http://www.wingman-sw.com/images/wingman.png)](http://wingman-sw.com)

**Comment by basvodde** [comment]
Was this on linux? Checking this. I'm confused by the pull request changes though.

**Comment by offa** [comment]
> Would it be better to set this compile option so the tests can still run

If that's possible just for the test, that would be good.


> Was this on linux? Checking this. I'm confused by the pull request changes though.

Yes, but i also failed with clang on windows.

The PR solves the issues to be able to compile at least without tests on clang. I wasn't sure how to address this test issues so i've opend this issue.

**Comment by basvodde** [comment]
Hmm, I tried to get 3.7 on my Ubuntu, but it isn't packaged yet for the stable release. Want to have a look at this myself.

**Comment by offa** [comment]
I'm not on Ubuntu, but it seems you can get it from here: http://llvm.org/apt/

**Comment by basvodde** [comment]
Thanks, I'll have a look at it these days.
