### ISSUE TITLE
enabling -fsanitize=address when linking to CppUTest with memory leak checks enabled

### ISSUE THREAD

**Issue by jacob-keller** [cpputest/cpputest#1270]
I have some unit tests for code that use CppUTest. I want to enable the -fsanitize=address option to enable the libasan based address sanitizers and memory leak checking. I'm working in FreeBSD 11.3

When I enable -fsanitize=address, I see the following issues with the linker:

```
/usr/local/lib/libCppUTest.a(lib_libCppUTest_a-MemoryLeakWarningPlugin.o): In function `operator delete[](void*)':
src/CppUTest/MemoryLeakWarningPlugin.cpp:(.text+0xe0): multiple definition of `operator delete[](void*)'
/usr/lib/clang/8.0.0/lib/freebsd/libclang_rt.asan_cxx-x86_64.a(asan_new_delete.o):asan_new_delete.cc:(.text+0xdc0): first defined here
/usr/local/lib/libCppUTest.a(lib_libCppUTest_a-MemoryLeakWarningPlugin.o): In function `operator delete[](void*, unsigned long)':
src/CppUTest/MemoryLeakWarningPlugin.cpp:(.text+0x100): multiple definition of `operator delete[](void*, unsigned long)'
/usr/lib/clang/8.0.0/lib/freebsd/libclang_rt.asan_cxx-x86_64.a(asan_new_delete.o):asan_new_delete.cc:(.text+0x13c0): first defined here
/usr/local/lib/libCppUTest.a(lib_libCppUTest_a-MemoryLeakWarningPlugin.o): In function `operator delete(void*)':
src/CppUTest/MemoryLeakWarningPlugin.cpp:(.text+0x70): multiple definition of `operator delete(void*)'
/usr/lib/clang/8.0.0/lib/freebsd/libclang_rt.asan_cxx-x86_64.a(asan_new_delete.o):asan_new_delete.cc:(.text+0xc40): first defined here
/usr/local/lib/libCppUTest.a(lib_libCppUTest_a-MemoryLeakWarningPlugin.o): In function `operator delete(void*, unsigned long)':
src/CppUTest/MemoryLeakWarningPlugin.cpp:(.text+0x90): multiple definition of `operator delete(void*, unsigned long)'
/usr/lib/clang/8.0.0/lib/freebsd/libclang_rt.asan_cxx-x86_64.a(asan_new_delete.o):asan_new_delete.cc:(.text+0x1240): first defined here
/usr/local/lib/libCppUTest.a(lib_libCppUTest_a-MemoryLeakWarningPlugin.o): In function `operator new[](unsigned long)':
src/CppUTest/MemoryLeakWarningPlugin.cpp:(.text+0xa0): multiple definition of `operator new[](unsigned long)'
/usr/lib/clang/8.0.0/lib/freebsd/libclang_rt.asan_cxx-x86_64.a(asan_new_delete.o):asan_new_delete.cc:(.text+0x190): first defined here
/usr/local/lib/libCppUTest.a(lib_libCppUTest_a-MemoryLeakWarningPlugin.o): In function `operator new[](unsigned long, std::nothrow_t const&)':
src/CppUTest/MemoryLeakWarningPlugin.cpp:(.text+0x120): multiple definition of `operator new[](unsigned long, std::nothrow_t const&)'
/usr/lib/clang/8.0.0/lib/freebsd/libclang_rt.asan_cxx-x86_64.a(asan_new_delete.o):asan_new_delete.cc:(.text+0x490): first defined here
/usr/local/lib/libCppUTest.a(lib_libCppUTest_a-MemoryLeakWarningPlugin.o): In function `operator new(unsigned long)':
src/CppUTest/MemoryLeakWarningPlugin.cpp:(.text+0x30): multiple definition of `operator new(unsigned long)'
/usr/lib/clang/8.0.0/lib/freebsd/libclang_rt.asan_cxx-x86_64.a(asan_new_delete.o):asan_new_delete.cc:(.text+0x0): first defined here
/usr/local/lib/libCppUTest.a(lib_libCppUTest_a-MemoryLeakWarningPlugin.o): In function `operator new(unsigned long, std::nothrow_t const&)':
src/CppUTest/MemoryLeakWarningPlugin.cpp:(.text+0x110): multiple definition of `operator new(unsigned long, std::nothrow_t const&)'
/usr/lib/clang/8.0.0/lib/freebsd/libclang_rt.asan_cxx-x86_64.a(asan_new_delete.o):asan_new_delete.cc:(.text+0x320): first defined here
```

The only workaround I've found so far is to re-build CppUTest with memory leak checking completely disabled. I tried adding -DCPPUTEST_MEM_LEAK_DETECTION_DISABLED to the flags, but it somehow still ends up failing.

My version of clang is
```
FreeBSD clang version 8.0.0 (tags/RELEASE_800/final 356365) (based on LLVM 8.0.0)
Target: x86_64-unknown-freebsd11.3
Thread model: posix
InstalledDir: /usr/bin
```

I'm not really sure if this is an issue in CppUTest, LLVM/Clang, or my Makefile.

**Comment by jacob-keller** [comment]
[AllTests.cpp.txt](https://github.com/cpputest/cpputest/files/3957662/AllTests.cpp.txt)
[Makefile.txt](https://github.com/cpputest/cpputest/files/3957663/Makefile.txt)

This Makefile and AllTests.cpp should reproduce the failure. I'm not sure if this failure appears in other operating systems, and it may be due some issue in FreeBSD...

**Comment by vpod** [comment]
try `-DMEMORY_LEAK_DETECTION=OFF`

**Comment by jacob-keller** [comment]
> try `-DMEMORY_LEAK_DETECTION=OFF` if you use cmake to build cpputest; for autoconf there was some flag as well, I think
> 
> or do you mean that you want it temporarily?

I want to avoid rebuilding CppUTest. i.e. fix the linking issue or changing flags in the Makefile that I provided so that it builds without using CppUTest memory leak checks and links to the clang libasan.

This is possibly a bug/issue in the FreeBSD CppUTest package, or an issue in how clang links to libasan..? I don't see the same issue in Linux.

**Comment by jacob-keller** [comment]
You should be able to reproduce this issue in a FreeBSD 11.3 or 12.1 VM by installing the default cpputest package using pkg, and with the provided Makefile and AllTests.cpp file I gave above that has a minimal reproduction

**Comment by p0strom** [comment]
In my experience there is no other way other than rebuilding CppUTest with memory leak detection disabled. I have tried this on Windows with Cygwin and on Ubuntu 18.04 building CppUTest using CMake.

**Comment by basvodde** [comment]
I'm not sure what to do with this ?

If I read the address sanitizer, then it does the same as CppUTest in the same way. So... that is going to clash. Not sure how we can resolve that. Do we just need to add this to the documentation?

Any suggestions?

**Comment by jacob-keller** [comment]
Yea. I am not sure if this reproduced on other OS, so maybe there is some clever thing that a linker can do to avoid problems, given the "works in linux".

It also vaguely looks FreeBSD is using a staticly linked CppUTest library, rather than using a shared object library... Hmmmm

**Comment by basvodde** [comment]
Ok, I've added address-sanitizer support to CppUTest. It caused some failing tests.

Could you try to rebuild CppUTest with "configure --enable-santize-address CC=yourflavor CXX=etc" and use that lib. Perhaps that ought to work.

Creating a pull request in a moment.

**Comment by jacob-keller** [comment]
That still didn't fix things. I'm suspicious that this is a bug or flaw in the linker for FreeBSD 11.3, because the exact same test works in Linux on Fedora 31.

**Comment by basvodde** [comment]
You do not get these errors when building CppUTest itself, right ?

**Comment by jacob-keller** [comment]
No, as I pointed out in this comment:

> [AllTests.cpp.txt](https://github.com/cpputest/cpputest/files/3957662/AllTests.cpp.txt)
> [Makefile.txt](https://github.com/cpputest/cpputest/files/3957663/Makefile.txt)
> 
> This Makefile and AllTests.cpp should reproduce the failure. I'm not sure if this failure appears in other operating systems, and it may be due some issue in FreeBSD...

It's an issue building test cases with -fsanitize=address on a CppUTest build that had memory leak support enabled. Basically: I don't want to have to build a custom install of CppUTest, and would rather just use what's in FreeBSD's package repository.

This exact same Makefile and test file does *not* fail in Linux, leading me to believe it's a difference in either the linker, or compiler that somehow causes this to fail in FreeBSD.

I've started upgrading my FreeBSD 11.3 system to see if maybe this has been fixed in a newer version of FreeBSD. It's possible that this is simply because FreeBSD 11 used such an old version of the clang compiler and linker that it can't figure this out. I can't think of why else this would fail on FreeBSD but not Linux.

**Comment by basvodde** [comment]
Reproduced in build: https://travis-ci.org/github/cpputest/cpputest/jobs/679612175

**Comment by jacob-keller** [comment]
I also updated my FreeBSD system to FreeBSD 12.1, and I still see this issue.

**Comment by jacob-keller** [comment]
I just tried this on Fedora with clang++ instead of g++ and it reproduces the same as in FreeBSD, leading me to believe this is an issue in clang/LLVM.

**Comment by jacob-keller** [comment]
It looks like this is a known issue: https://bugs.llvm.org/show_bug.cgi?id=19660 in clang.

**Comment by basvodde** [comment]
Yeah, I'm likely going to automatically turn off the memory leak detector when clang/sanitizer is used. But... I'm amused that it doesn't happen in gcc. The MacOS clang/gcc seem fine. The Linux gcc reports a bunch of (known) leaks that I now decided to fix anyways. The Linux clang doesn't link.

Weird differences.

**Comment by jacob-keller** [comment]
Yep, gcc separates the c++ bits into another library.

If you enable leak checking, -fsanitize=leak, I believe gcc will also fail
to link.

**Comment by basvodde** [comment]
Interestingly, it is doing leak checking on Linux. Not so on Mac.

I got a lot of leaks due to the longjmp usage. I decided to fix these... but they are really really really hard to fix :)

**Comment by jacob-keller** [comment]
Interesting. I wonder how gcc manages to make that work but clang can't.

**Comment by basvodde** [comment]
Resolved. When using clang on linux with address sanitizer, the memory leak detection is automatically turned off and a warning is produced. Closing this.
