### PR TITLE
Fix for compilation errors related to isinf()

### LINKED ISSUE #709: Failed float/double cast prevents build on GCC 5.1
The current snapshot (b8f5ce0) fails to build by a conversion to float from double (`Werror=float-conversion)`.

 The cause is the function `int IsInfImplementation(double)` (`src/Platforms/Gcc/UtestPlatform.cpp:242:12`):

```cpp
static int IsInfImplementation(double d)
{
    return isinf(d); // Casting to d to float solves the issue
}
```
However, i'm not sure if this is cast safe.

--------------

`isinf()` is implemtend like this on GCC 5.1:

```cpp
#  define isinf(x) \
     (sizeof (x) == sizeof (float)					      \
      ? __isinff (x)							      \
      : sizeof (x) == sizeof (double)					      \
      ? __isinf (x) : __isinfl (x))
```

### PR DESCRIPTION
**Pull request by jgonzalezdr**
Fixes #709

### CODE REVIEW

File: src/Platforms/Gcc/UtestPlatform.cpp [hunk 1]
```diff
@@ -239,7 +239,7 @@ static int IsNanImplementation(double d)
 
 static int IsInfImplementation(double d)
 {
-    return isinf(d);
+    return isinf((float)d);
```
Comment (arstrube) [inline src/Platforms/Gcc/UtestPlatform.cpp]: Yeah, lets do this
