### ISSUE TITLE
Binary install on Ubuntu 18.04 missing some test macros?

### ISSUE THREAD

**Issue by BrettHemes** [cpputest/cpputest#1273]
I recently switched from a source build to installing the binary via `apt install cpputest` on Ubuntu 18.04 and am getting compiler errors complaining about CHECK_COMPARE not existing.

    error: ‘CHECK_COMPARE’ was not declared in this scope
    ...
    note: suggested alternative: ‘CHECK_FALSE’

After some grepping and inspection it seems the `UTestMacros.h` I get from the binary install is missing bits that are in the source branches.  A Git blame says that the `CHECK_COMPARE` define in the source is over 8 years old so I don't really know whats up.

Any thoughts?

**Comment by offa** [comment]
The [Ubuntu version](https://packages.ubuntu.com/bionic/cpputest) is outdated (v3.8 from 2016). The `CHECK_COMPAE()` macro isn't available in this version yet.

It has been introduced with 867ea44260ec4cabec2e0b55b9426bb15ace6169.

**Comment by basvodde** [comment]
Will try to release 3.9 soon. Closing this for now.
